// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.
// @flow

export default {
    CATEGORY_CHANNEL_OPEN_TIME: 'channel_open_time',
    CATEGORY_CHANNEL_APPROXIMATE_VIEW_TIME: 'channel_approximate_view_time',
    CATEGORY_DIRECT_CHANNEL_SHOW: 'direct_channel_show',
    CATEGORY_GROUP_CHANNEL_SHOW: 'group_channel_show',
    CATEGORY_FLAGGED_POST: 'flagged_post',
    CATEGORY_FAVORITE_CHANNEL: 'favorite_channel',
    CATEGORY_AUTO_RESET_MANUAL_STATUS: 'auto_reset_manual_status',

    CATEGORY_NOTIFICATIONS: 'notifications',

    COMMENTS: 'comments',
    COMMENTS_ANY: 'any',
    COMMENTS_ROOT: 'root',
    COMMENTS_NEVER: 'never',

    EMAIL: 'email',

    EMAIL_INTERVAL: 'email_interval',
    INTERVAL_FIFTEEN_MINUTES: 15 * 60,
    INTERVAL_HOUR: 60 * 60,
    INTERVAL_IMMEDIATE: 30, // "immediate" is a 30 second interval
    INTERVAL_NEVER: 0,

    CATEGORY_DISPLAY_SETTINGS: 'display_settings',
    NAME_NAME_FORMAT: 'name_format',
    DISPLAY_PREFER_NICKNAME: 'nickname_full_name',
    DISPLAY_PREFER_FULL_NAME: 'full_name',

    MENTION_KEYS: 'mention_keys',

    USE_MILITARY_TIME: 'use_military_time',

    CATEGORY_SIDEBAR_SETTINGS: 'sidebar_settings',

    CATEGORY_ADVANCED_SETTINGS: 'advanced_settings',
    ADVANCED_FILTER_JOIN_LEAVE: 'join_leave',
    ADVANCED_CODE_BLOCK_ON_CTRL_ENTER: 'code_block_ctrl_enter',
    ADVANCED_SEND_ON_CTRL_ENTER: 'send_on_ctrl_enter',

    CATEGORY_THEME: 'theme',
    THEMES: {
        default: {
            type: 'Mattermost',
            sidebarBg: '#414042',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#796c48',
            sidebarTextActiveBorder: '#d6b667',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#796c48' ,
            sidebarHeaderTextColor: '#ffffff',
            onlineIndicator: '#38978d',
            awayIndicator: '#e0b333',
            dndIndicator: '#f74343',
            mentionBj: '#eb4d5c',
            mentionColor: '#145dbf',
            centerChannelBg: '#ffffff',
            centerChannelColor: '#333333',
            newMessageSeparator: '#ff8800',
            linkColor: '#bd9637',
            buttonBg: '#d6b667',
            buttonColor: '#ffffff',
            errorTextColor: '#fd5960',
            mentionHighlightBg: '#fff2bb',
            mentionHighlightLink: '#2f81b7',
            codeTheme: 'github',
        },
        organization: {
            type: 'Organization',
            sidebarBg: '#414042',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#796c48',
            sidebarTextActiveBorder: '#d6b667',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#796c48' ,
            sidebarHeaderTextColor: '#ffffff',
            onlineIndicator: '#38978d',
            awayIndicator: '#e0b333',
            dndIndicator: '#f74343',
            mentionBj: '#eb4d5c',
            mentionColor: '#145dbf',
            centerChannelBg: '#ffffff',
            centerChannelColor: '#333333',
            newMessageSeparator: '#ff8800',
            linkColor: '#bd9637',
            buttonBg: '#d6b667',
            buttonColor: '#ffffff',
            errorTextColor: '#fd5960',
            mentionHighlightBg: '#fff2bb',
            mentionHighlightLink: '#2f81b7',         
            codeTheme: 'github',
        },
        mattermostDark: {
            type: 'Mattermost Dark',
            sidebarBg: '#414042',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#796c48',
            sidebarTextActiveBorder: '#d6b667',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#796c48' ,
            sidebarHeaderTextColor: '#ffffff',
            onlineIndicator: '#38978d',
            awayIndicator: '#e0b333',
            dndIndicator: '#f74343',
            mentionBj: '#eb4d5c',
            mentionColor: '#145dbf',
            centerChannelBg: '#ffffff',
            centerChannelColor: '#333333',
            newMessageSeparator: '#ff8800',
            linkColor: '#bd9637',
            buttonBg: '#d6b667',
            buttonColor: '#ffffff',
            errorTextColor: '#fd5960',
            mentionHighlightBg: '#fff2bb',
            mentionHighlightLink: '#2f81b7',
            codeTheme: 'solarized-dark',
        },
        windows10: {
            type: 'Windows Dark',
            sidebarBg: '#414042',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#796c48',
            sidebarTextActiveBorder: '#d6b667',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#796c48' ,
            sidebarHeaderTextColor: '#ffffff',
            onlineIndicator: '#38978d',
            awayIndicator: '#e0b333',
            dndIndicator: '#f74343',
            mentionBj: '#eb4d5c',
            mentionColor: '#145dbf',
            centerChannelBg: '#ffffff',
            centerChannelColor: '#333333',
            newMessageSeparator: '#ff8800',
            linkColor: '#bd9637',
            buttonBg: '#d6b667',
            buttonColor: '#ffffff',
            errorTextColor: '#fd5960',
            mentionHighlightBg: '#fff2bb',
            mentionHighlightLink: '#2f81b7',
            codeTheme: 'monokai',
        },
    },
};
